name: CD

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publishing for ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        job:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.job.target }}
      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross

      - name: cargo xtask dist
        run: cargo xtask dist --use-cross-if-needed --target ${{ matrix.job.target }}
        shell: bash

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          path: target/dist/*

      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: target/dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
