name: Deploy Rustdoc to GitHub Pages

on:
  push:
    branches:
      - $default-branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    name: "Publishing GitHub Pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: rust
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain add nightly --profile minimal
      - run: cargo xtask docsrs --workspace
      - uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc

  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-docs]
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
